### ISSUE TITLE
Beta and Dev versions behind

### ISSUE THREAD

**Issue by shlozm** [ivan-hc/MS-Edge-appimage#3]
https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/microsoft-edge-beta_121.0.2277.4-1_amd64.deb
https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/microsoft-edge-dev_121.0.2277.4-1_amd64.deb

Can you fix those as well?

Thanks again!

**Comment by shlozm** [comment]
Maybe this can help ...
https://www.catalog.update.microsoft.com/Search.aspx?q=microsoft%20edge%20beta
https://www.catalog.update.microsoft.com/Search.aspx?q=microsoft%20edge%20dev
There's also this, but your repology method works well...
https://www.catalog.update.microsoft.com/Search.aspx?q=microsoft%20edge%20stable

**Comment by ivan-hc** [comment]
All I had to do was to use `sort --version-sort` from each page of the repository

**Comment by ivan-hc** [comment]
PS: according to the main repo, DEV and BETA are the same

https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/

https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/

**Comment by shlozm** [comment]
Great! Thanks a lot.

**Comment by shlozm** [comment]
> PS: according to the main repo, DEV and BETA are the same
> 
> https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-beta/
> 
> https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-dev/

Yes I noticed that too. It's not always the same so it's good that your building them separately.
