### ISSUE TITLE
error gbm wrapper.cc(74) & (257)

### ISSUE THREAD

**Issue by NOTURFRIENDBTW** [ivan-hc/MS-Edge-appimage#5]
i got error issue both on chrome & edge, i had no idea how to fix it
```
[21051:21051:0519/025837.657268:ERROR:gbm_wrapper.cc(74)] Failed to get fd for plane.: No such file or directory (2)
[21051:21051:0519/025837.657444:ERROR:gbm_wrapper.cc(257)] Failed to export buffer to dma_buf: No such file or directory (2)

```
![Screenshot at 2024-05-19 02-58-43](https://github.com/ivan-hc/MS-Edge-appimage/assets/79923098/9bc59b6e-bfbd-4fe5-bbb5-14a3c4a600b8)

**Comment by ivan-hc** [comment]
Please, try to run one of the appimages like this:
```
LD_DEBUG=libs ./*.AppImage
```
and let me see the log

**Comment by ivan-hc** [comment]
in the meantime this is what I've found by googleeing "error gbm wrapper":
- https://forum.magicmirror.builders/topic/18161/error-gbm_wrapper-cc-253-failed-to-export-buffer-to-dma_buf-no-such-file-or-directory
- https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/68

**Comment by NOTURFRIENDBTW** [comment]
i somehow fix it by changing kernel into liquorix 6.8.9 then back into arch kernel 6.9.1

**Comment by ivan-hc** [comment]
so was this problem related to the GPU or some hardware component?

if you can no longer reproduce the bug, can we close this issue?

**Comment by NOTURFRIENDBTW** [comment]
Yeah sure, even though its still showing these error when running on terminal but at least the app can be opened now
